{
    'name': "Library Management System",
    'author': "Abdo Mohamed",
    'category': "",
    'version': '17.0.0.1.0',
    'depends': ['base',
                'mail',
                'contacts',
                'web',
                ],
    'data': [
        'security/library_security.xml',
        'security/ir.model.access.csv',
        'data/books_seq.xml',
        'data/library_book_category_data.xml',
        'data/author_data.xml',
        'data/publisher_data.xml',
        'data/books_data.xml',
        'data/member_data.xml',
        'data/reservation_data.xml',
        'data/borrowing_data.xml',
        'data/borrowing_line_data.xml',
        'data/library_email_templates.xml',
        'data/library_cron_jobs.xml',
        'views/library_views.xml',
        'views/library_author_view.xml',
        'views/library_publisher_view.xml',
        'views/library_member_view.xml',
        'views/library_books_view.xml',
        'views/library_books_view_inherit.xml',
        'views/library_book_reservation_views.xml',
        'views/borrowing_rec_view.xml',
        'wizard/library_change_status_wizard_view.xml',
        'reports/books_report.xml',
        'reports/library_member_card_report.xml',
        'reports/author_publisher_reports.xml',
        'reports/borrowing_reservation_reports.xml',
    ],
    'assets': {
      'web.assets_backend': ['library/static/src/css/library_styles.css',
      'library/static/src/components/listView/listView.css',
      'library/static/src/components/listView/listView.js',
      'library/static/src/components/listView/listView.xml',
      'library/static/src/components/library_statistics/library_statistics.js',
      'library/static/src/components/library_statistics/library_statistics.xml',
      ],
      'web.report_assets_common': [
          'library/static/src/scss/library_report.scss',
      ],
    },
    'application': True,
}